services:
  - type: web
    name: webmuabandodungcu
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
